### ISSUE TITLE
Molfile import leads to incorrect results if atom labels not continous and increasing

### ISSUE THREAD

**Issue by schatzsc** [JanCBrammer/TUCAN#58]
According to the BIOVIA definition the only limitation for the atom index in the ATOM block of a molfile is:

"Integer > 0 Identifies atoms. The actual value of the index does not matter as long as each index is unique to each atom."

Therefore, the following molfile is correct and not withstanding some problems with implict H addition due to bond orders just set to 1 to simplify things, should have the Ni atom in the center coordinated to four C from the CO ligands:

NiCO4.mol
 nickel(0) tetracarbonyl

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 9 8 0 0 0
M  V30 BEGIN ATOM
M  V30 6 Ni 0.0 0.0 0.0000 0
M  V30 1 C 0.0 0.0 0.0000 0
M  V30 2 O 0.0 0.0 0.0000 0
M  V30 3 C 0.0 0.0 0.0000 0
M  V30 4 O 0.0 0.0 0.0000 0
M  V30 5 O 0.0 0.0 0.0000 0
M  V30 7 O 0.0 0.0 0.0000 0
M  V30 8 C 0.0 0.0 0.0000 0
M  V30 9 C 0.0 0.0 0.0000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 6 1
M  V30 2 1 6 3
M  V30 3 1 6 9
M  V30 4 1 6 8
M  V30 5 1 1 7
M  V30 6 1 3 4
M  V30 7 1 8 5
M  V30 8 1 9 2
M  V30 END BOND
M  V30 END CTAB
M  END

TUCAN however handles this incorrectly, leading to string

C4NiO4/1-3/2-6/3-8/4-5/4-8/6-8/7-9/8-9

instead of proper

C4NiO4/1-5/1-9/2-6/2-9/3-7/3-9/4-8/4-9

<img width="359" alt="nico" src="https://user-images.githubusercontent.com/88166560/173922041-1d30c55f-c51f-4059-9123-da23de0d9500.png">

Also, problems arise with the * pseudo-atom which needs to be ignored in the ATOM block as well as node and edge creation while the ENDPTS statement in the bond block has to be expanded as shown below (but one has to keep track of whether 7 or 11 is the pseudoatom, since unfortunately, this is not consistently kept as either first or second (4th or 5th column in 1-based counting of the line):

M  V30 9 1 7 11 ENDPTS=(2 1 2) ATTACH=ANY

**Comment by JanCBrammer** [comment]
Good catch. See 531c22f98495083dd5cf6ea437558824813f2eaa. Can you check if it works now?
