### ISSUE TITLE
Problem with canonicalization: not only atomic number but also label and partitions to be "zero-filled"?

### ISSUE THREAD

**Issue by schatzsc** [JanCBrammer/TUCAN#59]
Canonicalization of nitrobenzene does not give expected result:

Carbon atoms 7 and 8 should be exchanged and also H attachment incorrect, should pair C9-H4, C8-H3, C7-H2, C6-H1, C5-H0 and C5 para to nitro group:

<img width="344" alt="nitrobenzene" src="https://user-images.githubusercontent.com/88166560/173923981-1b4a5a66-7cdf-427a-b6aa-7a91772acc7a.png">

Possible reason behind incorrect assignment:

also need to fill label and partition number with leading zeros if atom index > 9 ?!? Some lines do not sort as expected:

refinement iteration 3
label    invariants    partition    neighbors (label, invariants, partition)
-------  ------------  -----------  ------------------------------------------
0        001           0            (5, 006, 3)
**1        001           1            (7, 006, 4)
2        001           1            (6, 006, 4)
3        001           2            (9, 006, 5)
4        001           2            (8, 006, 5)**
5        006           3            (6, 006, 4), (7, 006, 4), (0, 001, 0)
**6        006           4            (8, 006, 5), (5, 006, 3), (2, 001, 1)
7        006           4            (9, 006, 5), (5, 006, 3), (1, 001, 1)**
**8        006           5            (10, 006, 6), (6, 006, 4), (4, 001, 2)
9        006           5            (10, 006, 6), (7, 006, 4), (3, 001, 2)**
10       006           6            (11, 007, 7), (8, 006, 5), (9, 006, 5)
11       007           7            (12, 008, 8), (13, 008, 8), (10, 006, 6)
12       008           8            (11, 007, 7)
13       008           8            (11, 007, 7)

**Comment by schatzsc** [comment]
I wonder what happens if you have **more than nine partitions**? Are the partition numbers also compared in a lexicographical way? I think it would possibly be much more easy to make both atomic number and partition number integer (int) data, in particular since for very large molecules, there is at least in principle no upper limit to the partitions, so with how many zeros should you fill in?!?

**Comment by JanCBrammer** [comment]
> I think it would possibly be much more easy to make both atomic number and partition number integer

The partitions are already treated as integers. For the atomic numbers this is also the case now: 3b9eb07.

**Comment by JanCBrammer** [comment]
> also need to fill label and partition number with leading zeros if atom index > 9 ?!? Some lines do not sort as expected:

The labels (aka atom indices) have no influence on the sorting. The sorting goes only by either atomic number or partition.

**Comment by JanCBrammer** [comment]
> Canonicalization of nitrobenzene does not give expected result:

Since we're using the bliss algorithm to assign the canonical labels, we cannot explicitly influence the exact order of labels within a partition. However, note that this is only an "aesthetic" problem, it doesn't affect the correctness of the canonicalization.

**Comment by schatzsc** [comment]
Suggest for the moment to stay with the current scheme and first fix all the issues needed for the manuscript revision, but at some stage we should come back to the canonicalization. Also, the "ring invariant" is still nagging me.

**Comment by JanCBrammer** [comment]
> Suggest for the moment to stay with the current scheme and first fix all the issues needed for the manuscript revision, but at some stage we should come back to the canonicalization.

Agreed. Closing for now.
