### ISSUE TITLE
Extend parsing of ATOM block in molfile: need to also read in CHG, MASS and RAD fields

### ISSUE THREAD

**Issue by schatzsc** [JanCBrammer/TUCAN#60]
So far, the molfile parser only extracts the element symbol from the v3000 molfile bond block in `parse_molfile3000()` using

`element_symbols = [`
`l[3] for l in lines[atom_block_offset : atom_block_offset + atom_count]`
`]`

However, the field CHG, MASS, and RAD for non-zero atomic charge, non-standard isotopes, and multiplicity also need to be read in, assigned as node attributes and passed on to the TUCAN string. The tricky part here is that they can appear in any order and also mixed with other fields which we do not want to consider, since they are only relevant to handling of stereochemistry (which we want to do later and differently from the "wedged bonds") and "standard valence".

**Comment by schatzsc** [comment]
My solution to this is in the `add_node_properties()` function, which also reads in the (pseudo)-3D coordinates
[tucan2_main.txt](https://github.com/JanCBrammer/TUCAN/files/8971938/tucan2_main.txt)
.

**Comment by schatzsc** [comment]
First sets a number of required node attributes with

            attrs = {int(l[2]): {"node_label": int(l[2]),
                                 "partition": 0,
                                 "invariant_code": "",
                                 "element_symbol": l[3],
                                 "element_name": ELEMENT_PROPS[l[3]]['element_name'],
                                 "atomic_number": ELEMENT_PROPS[l[3]]['atomic_number'],
                                 "x_coord": float(l[4]),
                                 "y_coord": float(l[5]),
                                 "z_coord": float(l[6]),
                                 "fragment": 0,
                                 "color": color}}
            nx.set_node_attributes(graph, attrs)

and then - only if they were present in the molfile - additionally sets

            if(has_charge == True):
                attrs = {int(l[2]): {"charge": charge}}
                nx.set_node_attributes(graph, attrs)
            if(has_isotope == True):
                attrs = {int(l[2]): {"isotope": isotope}}
                nx.set_node_attributes(graph, attrs)
            if(has_radical == True):
                attrs = {int(l[2]): {"multiplicity": radical}}
                nx.set_node_attributes(graph, attrs)

with charge for CHG, isotope for MASS, and multiplicity for RAD, with the latter two more intuitive names for those fields/variables.

**Comment by JanCBrammer** [comment]
For reference: https://discover.3ds.com/sites/default/files/2020-08/biovia_ctfileformats_2020.pdf

**Comment by JanCBrammer** [comment]
Do you have representative .mol files that contain the CHG, MASS, and RAD properties? Would be handy for writing tests. In our test set, we have a few files that contain CHG, but not MASS or RAD.

**Comment by JanCBrammer** [comment]
See https://github.com/JanCBrammer/TUCAN/blob/7be8a8a469c60a627a80d2cde77cabe54bf46b32/tucan/io.py#L65-L82

**Comment by schatzsc** [comment]
So the "chg", "mass", and "rad" node attributes are always set, regardless of whether they are defined in the molfile or not?!?

Of course makes processing of data structure easier but is also less memory-efficient, as for insulin with a couple of hundred atoms, most of them will have none of these attributes set.

Current approach is easy implementation over saving space.

Furthermore, I'm not sure if setting all of them to zero is a good idea, since zero is a valid number, should rather be set in some way to "undefined"

**Comment by schatzsc** [comment]
@JanCBrammer Also need to add CHG, MASS and RAD to the TUCAN string in output - suggest to use the following code in `serialize_molecule()` after the `for edge in _edge_list` loop:

    ###
    serialization += "/"
    for n in sorted(m.nodes):
        k = m.nodes[n].keys()
        node_attributes_flag = False
        charge_string = ""
        isotope_string = ""
        multiplicity_string = ""
        aux_data_string = ""
        for attr in sorted(k):
            if not(attr in ['node_label', 'partition', 'invariant_code', 'element_symbol', 'element_name', 'atomic_number', 'x_coord', 'y_coord', 'z_coord', 'fragment', 'color', 'charge', 'isotope', 'multiplicity']):
                attr_value = nx.get_node_attributes(m, attr)[n]
                if(attr_value != 0):
                    aux_data_string += str(attr)+"="+str(attr_value)+","
                    node_attributes_flag = True
        if("charge" in k):
            charge = nx.get_node_attributes(graph, "charge")[n]
            charge_string = "CHG="+str(charge)+","
            node_features_flag = True
        if("isotope" in k):
            isotope = nx.get_node_attributes(g, "isotope")[n]
            isotope_string = "MASS="+str(isotope)+","
            node_attributes_flag = True
        if("multiplicity" in k):
            multiplicity = nx.get_node_attributes(g, "multiplicity")[n]
            multiplicity_string = "RAD="+str(multiplicity)+","
            node_attributes_flag = True
        if(node_attributes_flag == True):
            serialization += "("+str(n)+":"+charge_string+isotope_string+multiplicity_string
            if(aux_data_string != ""):
                serialization = serialization + aux_data_string
            if(serialization[-1:] == ","):
                serialization = serialization[:-1]
            serialization += ")"
    if(serialization[-2:] == "//"):
        serialization = serialization[:-2]
    if(serialization[-1:] == "/"):
        serialization = serialization[:-1]

**Comment by JanCBrammer** [comment]
@schatzsc 

> So the "chg", "mass", and "rad" node attributes are always set, regardless of whether they are defined in the molfile or not?!?

We don't set a default for optional node properties anymore, see 1cc4936.


> I'm not sure if setting all of them to zero is a good idea, since zero is a valid number, should rather be set in some way to "undefined"

According to the specification (https://discover.3ds.com/sites/default/files/2020-08/biovia_ctfileformats_2020.pdf) of CHG and RAD "0 = none (default)." Not sure if 0 is also a good default for MASS. However, the point regarding defaults is mute since we're not using them anymore (see 1cc4936).



> Also need to add CHG, MASS and RAD to the TUCAN string in output

Could you post a an example string?


It would be good to have a few test-files that contain CHG, MASS, and RAD. Currently, we only have files that contain CHG.

**Comment by JanCBrammer** [comment]
We start with the following general format (personal communication): 

`<sum formula>/(<node label>-<node label>)(<node label>-<node label>)...(<node label>-<node label>)/(<node label>:<property name>=<property value>,<property name>=<property value>)(<node label>:<property name>=<property value>)...(<node label>:<property name>=<property value>)`

**Comment by JanCBrammer** [comment]
@schatzsc, see a6fd9932b4a7a9d4c6693a53f952caa0adb5bb93. The serialization now follows the specification above.

**Comment by schatzsc** [comment]
How extensible is this towards additional "node attributes" and in particular "custom node attributes" which are not from the molfile definition but defined by a user in the "SDblock"?

    optional_props = {
        "chg": [int(i.split("=")[1]) for i in line if "CHG" in i],
        "mass": [int(i.split("=")[1]) for i in line if "MASS" in i],
        "rad": [int(i.split("=")[1]) for i in line if "RAD" in i],
    }
    
defines the "standard node attributes", right? Is this the only required defintion or do you also need to change something in the output routines if an additional node attribute is defined here?

**Comment by flange-ipb** [comment]
Another thing that might need consideration sooner or later:
The atom properties may span several lines in the molfile. This is mentioned on page 6 of BIOVIA's CTFile specification, i.e. lines longer than 80 characters need to be split with a '-'. You can also see this in the first example of the "Atom Block" section at the end of page 7 (which is misformatted by the way). Seems they still use punch cards over at BIOVIA ...

**Comment by schatzsc** [comment]
You're right about the longer lines. Not sure if this is relevant, as even a very long line like

`M  V30 7 Pt 0.845890 1.087110 0.000000 0 CHG=2 MASS=196`

is only 55 characters long. If you also add the RAD=x variable, which is very rarely used, that would add another five characters, so you're still left with another 20 (80-55-5). If it is easy to implement, ok - otherwise I'd give it low priority.

**Comment by schatzsc** [comment]
But we need a better check of input validity anyway.

For example, currently it is not check, as far as I know, if the atom index numbers used in the BOND block match those from the ATOM block.

Thus, you could have a case where an index number is used in the BOND block that is never defined in the ATOM block, as ` _parse_bond_block_molfile3000()` only checks if the number of bonds is equal to that defined in the `COUNTS` line, but does not check if it is in the ATOM block.

The background of this problem is that atom index numbers in the ATOM block do not need to be continuous. For example, the molfile for water can be

`water.mol
 water

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 3 2 0 0 0
M  V30 BEGIN ATOM
M  V30 1 H   0  0  0  0
M  V30 2 O  0  0  0  0
M  V30 3 H   0  0  0  0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1  2
M  V30 2 1 3  2
M  V30 END BOND
M  V30 END CTAB
M  END`

but it would also be valid as

`
water.mol
 water

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 3 2 0 0 0
M  V30 BEGIN ATOM
M  V30 42 H   0  0  0  0
M  V30 666 O  0  0  0  0
M  V30 1 H   0  0  0  0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 42  666
M  V30 2 1 666  1
M  V30 END BOND
M  V30 END CTAB
M  END
`

as the only requirement for the atom index numbers in the ATOM block is that they do not repeat (two atoms assigned the same index number).

Now, you could also have a molfile for water which is

`water.mol
 water

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 3 2 0 0 0
M  V30 BEGIN ATOM
M  V30 1 H   0  0  0  0
M  V30 2 O  0  0  0  0
M  V30 3 H   0  0  0  0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1  4
M  V30 2 1 3  5
M  V30 END BOND
M  V30 END CTAB
M  END`

that is obviously invalid since there are no atoms 4 and 5 but I guess currently TUCAN would create a 5-node graph for that, since `graph.add_edges_from(bonds)` does not require that the nodes defined in `bonds` already exits - if not, they will be created at run of this routine.

**Comment by JanCBrammer** [comment]
@flange-ipb, @schatzsc, absolutely. Our approach to reading molfiles currently is "good enough", but far from complete and reliable. I suggest we move this to another issue ("Molfile validation") for the roadmap?

**Comment by flange-ipb** [comment]
Do we need to reinvent the wheel, i.e. supply a new Molfile parser with TUCAN? I think we can also extract this information using rdkit: Its [Atom class](https://www.rdkit.org/docs/source/rdkit.Chem.rdchem.html#rdkit.Chem.rdchem.Atom) has methods to extract CHG (`GetFormalCharge()`), MASS (`GetIsotope()`) and RAD (`GetNumRadicalElectrons()`) and they return 0 in case the atom property was not specified.

**Comment by JanCBrammer** [comment]
Discussion moved to #66
