### ISSUE TITLE
Calculation of sum formula wrong for C1 compounds

### ISSUE THREAD

**Issue by schatzsc** [JanCBrammer/TUCAN#63]
I have a problem with the attached molfile of methanol, which produces a TUCAN string of 

H4O/(1-5)(2-5)(3-5)(4-6)(5-6)

which contains the expected five bonds (3x C-H, 1x C-O, and 1x O-H) in the proper way but the sum formula is wrong, should be CH4O instead of H4O. Is correct for ethanol which gives "C2H6O/(1-7)(2-7)(3-7)(4-8)(5-8)(6-9)(7-8)(8-9)" but also wrong for chloroform which gives "Cl3H/(1-2)(2-3)(2-4)(2-5)" instead of correct "CHCl3/(1-2)(2-3)(2-4)(2-5)", so seems to be related to single leading C without following number ....

methanol.mol
  ChemDraw07172201442D

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 6 5 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 0.000000 0.206250 0.000000 0
M  V30 2 H 0.714471 0.618750 0.000000 0
M  V30 3 H -0.714471 0.618750 0.000000 0
M  V30 4 O 0.000000 -0.618750 0.000000 0
M  V30 5 H 0.000000 1.031250 0.000000 0
M  V30 6 H 0.714471 -1.031250 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 1 3
M  V30 3 1 1 4
M  V30 4 1 1 5
M  V30 5 1 4 6
M  V30 END BOND
M  V30 END CTAB
M  END

**Comment by JanCBrammer** [comment]
@schatzsc, good catch! Bug should be fixed with 2ed6e06ad871055da818363cac28616e50a738a7.
