### ISSUE TITLE
CHG label assignment incorrect

### ISSUE THREAD

**Issue by schatzsc** [JanCBrammer/TUCAN#64]
Something is wrong with the CHG label assignment (and possibly also MASS and RAD):

Depending on where on the attached molfile I put the CHG variable (atom 6 or 7) I get two different TUCAN strings:

C2H3O2/(1-4)(2-4)(3-4)(4-5)(5-6)(5-7)/(6:chg=-1)
C2H3O2/(1-4)(2-4)(3-4)(4-5)(5-6)(5-7)/(5:chg=-1)

Strangely, the 2nd line is obtained when CHG is on carbon atom 7 while the 1st line when it is on carbon 6. Is there maybe still a problem with zero- vs. one-based counting of the nodes?

acetate.mol
  ChemDraw10312101322D

  0  0  0     0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 7 6 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -0.357235 0.000000 0.000000 0
M  V30 2 C 0.357235 0.412500 0.000000 0
M  V30 3 H 1.071706 0.000000 0.000000 0
M  V30 4 H 0.357235 1.237500 0.000000 0
M  V30 5 H 1.071706 0.825000 0.000000 0
M  V30 6 O -1.071706 0.412500 0.000000 0 CHG=-1
M  V30 7 O -0.357235 -0.825000 0.000000 0 
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 2 3
M  V30 3 1 2 4
M  V30 4 1 2 5
M  V30 5 2 1 6
M  V30 6 1 1 7
M  V30 END BOND
M  V30 END CTAB
M  END

**Comment by schatzsc** [comment]
More specifically

_write_edge_list(m)

uses

[f"({edge[0] + 1}-{edge[1] + 1})" for edge in sorted_edges]

while

_write_node_properties(m):

uses

node_property_string += f"({label}:"

Need to change to (label + 1) ???

**Comment by JanCBrammer** [comment]
While serializing the node properties, the labels where indeed 0-based, not 1-based. Fixed with 635c565a4bc0d202461967cb579912ece324ea35.

**Comment by schatzsc** [comment]
Check, ok, closing
